mu: 1.25e-8
datasets:
   YRI:
    manifest: "resources/yri.manifest.tsv"
    popfile: "sandbox/yri_samples.txt"
    focal_indiv:
      - "NA18486"
      - "NA18487"
      - "NA18488"
      - "NA18489"
    t1: 20
    knots: 20
   CEU: 
    manifest: "resources/ceu.manifest.tsv"
    popfile: "sandbox/ceu_samples.txt"
    focal_indiv:
      - "NA06984"
      - "NA06985"
    t1: 20
    knots: 20
single_pop_demography:
  enabled: True
  populations:
    - "CEU"
    - "YRI"
split_time_estimates:
  enabled: False
  populations:
    - "CEU"
    - "YRI"
bootstrap:
  enabled: False
  nbootstrap: 10

