mu: 1.25e-8
datasets:
  bonobo:
    mask: ""
    contig_lengths: "data/results/bonobo/bonobo.biallelic.contig_stats.txt"
    manifest: "data/results/bonobo/bonobo.manifest.tsv"
    popfile: "data/results/bonobo/bonobo.samples.txt"
    focal_indiv:
      - "Bono"
      - "Catherine"
      - "Chipita"
    t1: 20
    knots: 20
single_pop_demography:
  enabled: True
  populations:
    - "bonobo"
split_time_estimate:
  enabled: False
  populations:
    - "bonobo"
bootstrap:
  enabled: False
  nbootstrap: 10
